version: '3.8'
services:
  account-db:
    image: postgres
    container_name: account-db-container
    expose:
      - 5432
    environment:
      POSTGRES_USER: app-account
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: account
    volumes:
      - account-db-data:/var/lib/postgresql/data
    networks:
      - account-network
  account-backend:
    build: .
    container_name: account-backend-container
    ports:
      - 8080:8080
    environment:
      db-url: r2dbc:postgresql://account-db:5432/account
      db-username: app-account
      db-password: admin
    networks:
      - account-network
      - bugShare-network
    depends_on:
      - account-db
networks:
  account-network:
    driver: bridge
  bugShare-network:
    driver: bridge
    name: bugshare-network
volumes:
  account-db-data: