version: '3.8'
services:
  db:
    image: postgres
    container_name: account-db-container
    ports:
      - 32768:5432
    environment:
      POSTGRES_USER: app-account
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: account
    volumes:
      - account-db-data:/var/lib/postgresql/data
  backend:
    build: .
    container_name: account-backend-container
    ports:
      - 8080:8080
    environment:
      db-url: r2dbc:postgresql://db:32768/account
      db-username: app-account
      db-password: admin
    depends_on:
      - db
volumes:
  account-db-data: