version: '3.8'
services:
  account-db:
    image: postgres
    container_name: account-db-container
    expose:
      - 5432
    environment:
      POSTGRES_USER: app-account
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: account
    volumes:
      - account-db-data:/var/lib/postgresql/data
    networks:
      - account-network
  account-backend:
    build: .
    container_name: account-backend-container
    ports:
      - 8081:8080
    environment:
      account-db-url: r2dbc:postgresql://account-db:5432/account
      account-db-username: app-account
      account-db-password: admin
      eureka.client.serviceUrl.defaultZone: http://bf-registry:8761/eureka/
    networks:
      - account-network
      - bf-network
    depends_on:
      - account-db
networks:
  account-network:
    driver: bridge
  bf-network:
    external: true
volumes:
  account-db-data: