version: '3.8'
services:
  account-db:
    image: postgres
    container_name: account-db-container
    expose:
      - 5432
    environment:
      POSTGRES_USER: app-account
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: account
    volumes:
      - account-db-data:/var/lib/postgresql/data
    networks:
      - account-network
  account-backend:
    build:
      context: .
    container_name: account-backend-container
#    restart: on-failure
    ports:
      - 8081:8080
#    environment:
#      SPRING_APPLICATION_NAME: account-service
#      SPRING_PROFILES_ACTIVE: dev
###      spring.cloud.config.import-check.enabled: false
##      SPRING_CLOUD_CONFIG_ENABLED: true
#      SPRING_CLOUD_CONFIG_URI: http://bf-config-server:8888
#      eureka.client.serviceUrl.defaultZone: http://bf-registry:8761/eureka/
#      eureka.client.fetchRegistry: true
#      eureka.registration.enabled: true
#      SPRING_APPLICATION_NAME: account-service
#      SPRING_PROFILES_ACTIVE: dev
#      spring.cloud.discovery.enabled: true
#      spring.cloud.discovery.service-id: bf-config-server

##      account-db-url: r2dbc:postgresql://account-db:5432/account
##      account-db-username: app-account
##      account-db-password: admin
#      eureka.client.serviceUrl.defaultZone: http://bf-registry:8761/eureka/
    networks:
      - account-network
      - bf-network
    depends_on:
      - account-db

networks:
  account-network:
    driver: bridge
  bf-network:
    external: true
volumes:
  account-db-data: